apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: An ICHP dedicated role for debugging.
    openshift.io/reconcile-protect: "true"
  creationTimestamp: "2024-03-08T22:14:44Z"
  labels:
    app.kubernetes.io/instance: rbac
    app.kubernetes.io/name: ichp-rbac
  name: ichp-project-debugger
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
