---
# Defaults for the deploy-rhbk role.
#rhbk:
#  namespace: keycloak
#  name: sso
#  db:
#    image: registry.redhat.io/rhel9/postgresql-15:latest
#    name: rhbk
#    username: rhbk
#    password: secret
#    claim_modes:
#      - ReadWriteOnce
#    size: 1Gi
#  realm: sample-realm
...
