---
# A simplistic inventory for the classroom VMs.
all:
  hosts:
    workstation.lab.example.com:
      ansible_connection: local
    utility.lab.example.com:
      ansible_user: lab
    bastion.lab.example.com:
      ansible_host: 172.25.250.254
      ansible_user: root
  vars:
    # OpenShift versions.
    ocp_maj: "4.16"
    ocp_z: "4.16.2"

    openshift:
      rhbk_client_id: openshift
      create_groups: yes
      egress_range: 192.168.50.128/26

    rhbk:
      namespace: keycloak
      realm: ichp
      clients:
        - id: openshift
          name: OpenShift OIDC Client
          secret: verysecret
          base_url: https://oauth-openshift.apps.ocp4.example.com
          direct_grants: false
      groups:
        - admins
        - developers
        - viewers
        - debuggers
      users:
        - username: johndoe
          password: redhat
          firstname: John
          lastname: Doe
          groups:
            - admins
        - username: janedoe
          password: redhat
          firstname: Jane
          lastname: Doe
          groups:
            - developers
        - username: tomjones
          password: redhat
          firstname: Tom
          lastname: Jones
          groups:
            - viewers
        - username: jsmith
          password: redhat
          firstname: James
          lastname: Smith
          groups:
            - debuggers

    # Operators that need to be (re)installed.
    #
    # The first item in the list is also used for checking whether catalog(s)
    # were recreated successfully.
    added_operators:
      - catalog: redhat-operators
        package: metallb-operator
        channel: stable
        namespace: metallb-system
        desired_csv: metallb-operator.v4.16.0-202507221936
        og_namespaces: []
        approval: Manual
      - catalog: redhat-operators
        package: rhbk-operator
        channel: stable-v26.2
        namespace: keycloak
        desired_csv: rhbk-operator.v26.2.7-opr.1
        og_namespaces:
          - keycloak
        approval: Manual
      - catalog: community-operators
        package: grafana-operator
        channel: v5
        namespace: grafana
        desired_csv: grafana-operator.v5.18.0
        og_namespaces: []
        approval: Manual
      - catalog: redhat-operators
        package: openshift-cert-manager-operator
        channel: stable-v1.17
        namespace: openshift-cert-manager
        desired_csv: cert-manager-operator.v1.17.0
        og_namespaces: []
        approval: Manual

    # Some cleanup here.
    removed_operators:
      - sub_nspc: openshift-cnv
        sub_name: kubevirt-hyperconverged
        csv_kill: yes
        csv_name: kubevirt-hyperconverged-operator.v4.16.1
        nsp_kill: yes
        pre_cleanup:
          - kind: hyperconverged
            apiv: hco.kubevirt.io/v1beta1
            nspc: openshift-cnv
            wait_for_gone: yes
            wait_for_sec: 600
        add_cleanup:
          - name: aaqs.aaq.kubevirt.io
          - name: cdis.cdi.kubevirt.io
          - label: operators.coreos.com/kubevirt-hyperconverged.openshift-cnv

    # The list of OpenShift clusters check-env will try to connect to.
    clusters:
      - ocp4
...
