---
# Check existing egress IP resources against their respective projects and remove verifiable orphans.
- name: Release existing egressip resources without a matching ICHP project.
  hosts: workstation.lab.example.com
  gather_subset: min
  become: no
  tasks:
    # Get auth info, and test comms.
    - include_role:
        name: check-env

    - include_role:
        name: purge-egress-ips
...
